# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [auto-build]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Fetch Latest DLL
        uses: robinraju/release-downloader@v1.3
        with:
          # The source repository path. Expected format {owner}/{repo}
          repository: aston-ambient/ambient-common
          latest: true
          fileName: ambient-common.dll
          out-file-path: ./Runtime/Plugins/
      - name: Update package.json
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: version
          value: ${{ github.event.client_payload.version }}
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v8.0.2
        with:
          author_name: vNemesis
          committer_name: vNemesis
          # The message for the commit
          message: 'Update to version: ${{ github.event.client_payload.version }}'
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.client_payload.version }}',
              sha: context.sha
            })

